name: Build - Emscripten

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "src/**"
      - ".github/workflows/build-emscripten.yml"
  push:
    paths:
      - "src/**"
      - ".github/workflows/build-emscripten.yml"
    branches:
      - main

jobs:
  cancel-runs:
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ github.token }}

  build:
    name: ${{ matrix.buildtype }}
    runs-on: ubuntu-latest

    concurrency:
      group: otclient-emscripten-${{ github.workflow }}-${{ github.ref }}-${{ matrix.buildtype }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        buildtype: [emscripten-debug]
        include:
          - buildtype: emscripten-debug
            cmake_build_type: Debug

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # por si browser/include/lua51 es submódulo

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "3.1.73"

      - name: Get vcpkg commit ID
        id: vcpkg-step
        run: |
          vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ')
          echo "vcpkgGitCommitId=$vcpkgCommitId" >> $GITHUB_OUTPUT

      # ✅ mover antes del cache
      - name: Compute vcpkg hash
        id: hash
        run: echo "hash=$(sha256sum vcpkg.json | cut -d' ' -f1)" >> $GITHUB_OUTPUT

      - name: Cache full vcpkg artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg/archives
            ${{ github.workspace }}/vcpkg/installed
            ${{ github.workspace }}/vcpkg/buildtrees
            ${{ github.workspace }}/vcpkg/downloads
          key: vcpkg-${{ matrix.buildtype }}-${{ steps.hash.outputs.hash }}
          restore-keys: |
            vcpkg-${{ matrix.buildtype }}-

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ${{ steps.vcpkg-step.outputs.vcpkgGitCommitId }}

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@v3.31.6

      - name: Configure CMake
        run: |
          cmake -G Ninja -S . -B build-${{ matrix.buildtype }} \
            -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=wasm32-emscripten \
            -DVCPKG_OVERLAY_PORTS=${{ github.workspace }}/browser/overlay-ports \
            -DVCPKG_BUILD_TYPE=${{ matrix.cmake_build_type }} \
            -DOPTIONS_ENABLE_IPO=OFF \
            -DTOGGLE_BIN_FOLDER=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
            -DTOGGLE_BOT_PROTECTION=OFF

      # ✅ nuevo: construir Lua 5.1 (liblua.a) para wasm en la ruta esperada
      - name: Build embedded Lua 5.1 for Emscripten
        run: |
          emmake make -C browser/include/lua51 clean || true
          emmake make -C browser/include/lua51 -j"$(nproc)"
          ls -l browser/include/lua51/liblua.a

      - name: Build
        run: |
          cmake --build build-${{ matrix.buildtype }} --target otclient -j"$(nproc)"

      - name: Create and Upload Artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: otclient-${{ matrix.buildtype }}-${{ github.sha }}
          path: ${{ github.workspace }}/build-${{ matrix.buildtype }}/bin/
          retention-days: 30
